function tentadayz(thePlayer)
local x, y, z = getElementPosition(thePlayer)
tent = createObject(964, x , y +4 , z -1)
setObjectScale(tent, 0.5)
tentCol = createColSphere(x , y, z,  4)
attachElements(tentCol, tent, 0, 0, 0)
setElementData(tentCol,"parent",tent);
setElementData(tent,"parent",tentCol);
setElementData(tentCol,"vehicle", false)
setElementData(tentCol,"tent",true);
setElementData(tentCol,"Watch", 1);
setElementData(tentCol,"MAX_Slots", 10000);
setElementData(tentCol,"item1", 1)
setElementData(tentCol,"toolbelt5", 1)
setElementData(tentCol,"weapon1", 1)
setElementData(tentCol,"weapon2", 1)
setElementData(tentCol,"weapon3", 1)
setElementData(tentCol,"weapon4", 1)
setElementData(tentCol,"weapon5", 1)
setElementData(tentCol,"weapon6", 1)
setElementData(tentCol,"weapon7", 1)
setElementData(tentCol,"weapon8", 1)
setElementData(tentCol,"weapon9", 1)
setElementData(tentCol,"weapon10", 1)
setElementData(tentCol,"weapon11", 1)
setElementData(tentCol,"weapon12", 1)
setElementData(tentCol,"weapon13", 1)
setElementData(tentCol,"weapon14", 1)
setElementData(tentCol,"weapon15", 1)
setElementData(tentCol,"weapon16", 1)
setElementData(tentCol,"weapon17", 1)
setElementData(tentCol,"weapon18", 1)
setElementData(tentCol,"weapon19", 1)
setElementData(tentCol,"weapon22", 1)
setElementData(tentCol,"weapon23", 1)
setElementData(tentCol,"weapon24", 1)
setElementData(tentCol,"weapon25", 1)
setElementData(tentCol,"weapon26", 1)
setElementData(tentCol,"weapon27", 1)
setElementData(tentCol,"weapon28", 1)
setElementData(tentCol,"weapon29", 1)
setElementData(tentCol,"weapon30", 1)
setElementData(tentCol,"fooditem9", 1)
setElementData(tentCol,"fooditem7", 1)
setElementData(tentCol,"fooditem6", 1)
setElementData(tentCol,"fooditem5", 1)
setElementData(tentCol,"fooditem4", 1)
setElementData(tentCol,"fooditem3", 1)
setElementData(tentCol,"fooditem2", 1)
setElementData(tentCol,"fooditem1", 1)
setElementData(tentCol,"item1", 1)
setElementData(tentCol,"item2", 1)
setElementData(tentCol,"item3", 1)
setElementData(tentCol,"item4", 1)
setElementData(tentCol,"item5", 1)
setElementData(tentCol,"item6", 1)
setElementData(tentCol,"item7", 1)
setElementData(tentCol,"item8", 1)
setElementData(tentCol,"item9", 1)
setElementData(tentCol,"item10", 1)
setElementData(tentCol,"item11", 1)
setElementData(tentCol,"item12", 1)
setElementData(tentCol,"item13", 1)
setElementData(tentCol,"item14", 1)
setElementData(tentCol,"item15", 1)
setElementData(tentCol,"item16", 1)
setElementData(tentCol,"item17", 1)
setElementData(tentCol,"item18", 1)
setElementData(tentCol,"item19", 1)
setElementData(tentCol,"item20", 1)
setElementData(tentCol,"backpack1", 1)
setElementData(tentCol,"backpack2", 1)
setElementData(tentCol,"backpack3", 1)
setElementData(tentCol,"backpack4", 1)
setElementData(tentCol,"backpack5", 1)
setElementData(tentCol,"backpack6", 1)
setElementData(tentCol,"backpack7", 1)
setElementData(tentCol,"backpack8", 1)
setElementData(tentCol,"medicine1", 1)
setElementData(tentCol,"medicine2", 1)
setElementData(tentCol,"medicine3", 1)
setElementData(tentCol,"medicine4", 1)
setElementData(tentCol,"medicine5", 1)
setElementData(tentCol,"medicine6", 1)
setElementData(tentCol,"medicine7", 1)
setElementData(tentCol,"medicine8", 1)
setElementData(tentCol,"medicine9", 1)
setElementData(tentCol,"medicine10", 1)
setElementData(tentCol,"vehiclepart1", 1)
setElementData(tentCol,"vehiclepart2", 1)
setElementData(tentCol,"vehiclepart3", 1)
setElementData(tentCol,"vehiclepart4", 1)
setElementData(tentCol,"vehiclepart5", 1)
setElementData(tentCol,"vehiclepart6", 1)
setElementData(tentCol,"vehiclepart7", 1)
setElementData(tentCol,"vehiclepart8", 1)
setElementData(tentCol,"vehiclepart9", 1)
setElementData(tentCol,"vehiclepart10", 1)
setElementData(tentCol,"clothing1", 1)
setElementData(tentCol,"clothing2", 1)
setElementData(tentCol,"clothing3", 1)
setElementData(tentCol,"clothing4", 1)
setElementData(tentCol,"clothing5", 1)
setElementData(tentCol,"clothing6", 1)
setElementData(tentCol,"clothing7", 1)
setElementData(tentCol,"clothing8", 1)
setElementData(tentCol,"vest1", 1)
setElementData(tentCol,"vest2", 1)
setElementData(tentCol,"helmet1", 1)
setElementData(tentCol,"helmet2", 1)
setElementData(tentCol,"helmet3", 1)
setElementData(tentCol,"helmet4", 1)
setElementData(tentCol,"helmet5", 1)
setElementData(tentCol,"helmet6", 1)
setElementData(tentCol,"helmet7", 1)
setElementData(tentCol,"mag1", 1)
setElementData(tentCol,"mag2", 1)
setElementData(tentCol,"mag3", 1)
setElementData(tentCol,"mag4", 1)
setElementData(tentCol,"mag5", 1)
setElementData(tentCol,"mag6", 1)
setElementData(tentCol,"mag7", 1)
setElementData(tentCol,"mag8", 1)
setElementData(tentCol,"mag9", 1)
setElementData(tentCol,"mag10", 1)
setElementData(tentCol,"toolbelt1", 1)
setElementData(tentCol,"toolbelt3", 1)
setElementData(tentCol,"toolbelt2", 1)
setElementData(tentCol,"toolbelt4", 1)
setElementData(tentCol,"toolbelt5", 1)
setElementData(tentCol,"toolbelt6", 1)
setElementData(tentCol,"toolbelt7", 1)
setElementData(tentCol,"toolbelt8", 1)
setElementData(tentCol,"toolbelt9", 1)




end
addCommandHandler("tenda", tentadayz)

--[[
addCommandHandler("tenda",
function (thePlayer)
	local x, y, z = getElementPosition(thePlayer)
	tent = createObject(964, x , y +4 , z -1)
	setObjectScale(tent, 2)
	local boxCol = createColSphere(x,y,z,4);
	attachElements(boxCol, tent, 0, 0, 0)
	setElementData(boxCol, "parent", tent)
	--attachElements(boxCol,loot_box,0,0,0);
	setElementData(boxCol,"parent",tent);
	setElementData(tent,"parent",boxCol);
	setElementData(boxCol,"tent",true);
	setElementData(boxCol,"supply_box",true);
    setElementData(boxCol, "Toolbox", 1);


end)]]