
addEventHandler ( "onPlayerJoin", root, function ( )
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox(" ", source)
	outputChatBox("#ff0000✔#ff6000___________________________________________________#ff0000✔", source, 255, 255, 255,true)
	outputChatBox("#dd76ff✔ #ff0000    "..getPlayerName(source).."#BDB76B Aziz Be Server #ffd700 Zombie MTA #BDB76BKhosh Omadid", source, 255, 255, 255, true)
	outputChatBox("#dd76ff✔ #BDB76B     Welcome To Zombie MTA Server!", source, 255, 255, 255,true)
	outputChatBox("#dd76ff✔ #BDB76B     Avalin Server Zombie Irani", source, 255, 255, 255,true)
	outputChatBox("#dd76ff✔ #BDB76B     Loading Game MTA, Please Wait...", source, 255, 255, 255,true)
	outputChatBox("#ff0000✔#ff6000___________________________________________________#ff0000✔", source, 255, 255, 255,true)
end )